[package]
name = "ere-prover-openvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
eyre.workspace = true
once_cell.workspace = true
thiserror.workspace = true

# OpenVM dependencies
openvm-circuit.workspace = true
openvm-sdk = { workspace = true, features = ["jemalloc", "parallel", "rvr"] }
openvm-sdk-config.workspace = true
openvm-stark-sdk.workspace = true
openvm-transpiler.workspace = true
openvm-verify-stark-host.workspace = true

# Local dependencies
ere-compiler-core.workspace = true
ere-prover-core.workspace = true
ere-verifier-openvm.workspace = true

[dev-dependencies]
ere-compiler-openvm.workspace = true
ere-util-test = { workspace = true, features = ["host"] }

[features]
default = []
cuda = ["openvm-sdk/cuda"]

[lints]
workspace = true
