[package]
name = "ere-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["catch-panic", "trace"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
twirp = { workspace = true }

# Local dependencies
ere-compiler-core = { workspace = true }
ere-prover-core = { workspace = true, features = ["clap"] }
ere-prover-openvm = { workspace = true, optional = true }
ere-prover-sp1 = { workspace = true, optional = true }
ere-prover-zisk = { workspace = true, optional = true }
ere-server-api.workspace = true

[features]
default = []

# zkVM
openvm = ["dep:ere-prover-openvm"]
sp1 = ["dep:ere-prover-sp1"]
zisk = ["dep:ere-prover-zisk"]

# Cuda
cuda = [
    "ere-prover-openvm?/cuda",
    "ere-prover-sp1?/cuda",
    "ere-prover-zisk?/cuda",
]

[[bin]]
name = "ere-server"
path = "src/main.rs"

[lints]
workspace = true
