//! [zkVM accelerator C interface] implemented on the OpenVM guest libraries.
//!
//! Accelerated by OpenVM intrinsics.
//! - `zkvm_keccak256`
//! - `zkvm_secp256k1_verify`
//! - `zkvm_secp256k1_ecrecover`
//! - `zkvm_sha256`
//! - `zkvm_modexp` (BN254 scalar field modulus only, other moduli run in software)
//! - `zkvm_bn254_g1_add`
//! - `zkvm_bn254_g1_mul`
//! - `zkvm_bn254_pairing`
//! - `zkvm_kzg_point_eval`
//! - `zkvm_bls12_g1_add`
//! - `zkvm_bls12_g1_msm`
//! - `zkvm_bls12_g2_add`
//! - `zkvm_bls12_g2_msm`
//! - `zkvm_bls12_pairing`
//! - `zkvm_secp256r1_verify`
//!
//! Implemented in software with no OpenVM intrinsic.
//! - `zkvm_ripemd160`
//! - `zkvm_blake2f`
//! - `zkvm_bls12_map_fp_to_g1`
//! - `zkvm_bls12_map_fp2_to_g2`
//!
//! [zkVM accelerator C interface]: https://github.com/eth-act/zkvm-standards/blob/main/standards/c-interface-accelerators/zkvm_accelerators.h
#![allow(non_camel_case_types)]

use alloc::{vec, vec::Vec};
use core::slice;

use ark_bls12_381::{Fq, Fq2, G1Affine, G2Affine};
use ark_ec::{
    AffineRepr,
    hashing::{curve_maps::wb::WBMap, map_to_curve_hasher::MapToCurve},
};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use openvm_curve_utils::SubgroupCheck;
use openvm_ecc_guest::{
    AffinePoint, Group,
    algebra::IntMod,
    weierstrass::{IntrinsicCurve, WeierstrassPoint},
};
use openvm_k256::ecdsa::{RecoveryId, Signature, VerifyingKey, signature::hazmat::PrehashVerifier};
use openvm_keccak256::keccak256;
use openvm_kzg::{Bytes32, Bytes48, EnvKzgSettings, KzgProof};
use openvm_p256::{
    EncodedPoint,
    ecdsa::{Signature as P256Signature, VerifyingKey as P256VerifyingKey},
};
use openvm_pairing::{
    PairingCheck,
    bls12_381::{self as bls, Bls12_381},
    bn254::{self as bn, Bn254},
};
use openvm_sha2::{Digest, Sha256};
use ripemd::{Digest as _, Ripemd160};
use zkvm_interface::{
    zkvm_blake2f_message, zkvm_blake2f_offset, zkvm_blake2f_state, zkvm_bls12_381_fp,
    zkvm_bls12_381_fp2, zkvm_bls12_381_g1_msm_pair, zkvm_bls12_381_g1_point,
    zkvm_bls12_381_g2_msm_pair, zkvm_bls12_381_g2_point, zkvm_bls12_381_pairing_pair,
    zkvm_bn254_g1_point, zkvm_bn254_pairing_pair, zkvm_bn254_scalar, zkvm_keccak256_hash,
    zkvm_kzg_commitment, zkvm_kzg_field_element, zkvm_kzg_proof, zkvm_ripemd160_hash,
    zkvm_secp256k1_hash, zkvm_secp256k1_pubkey, zkvm_secp256k1_signature, zkvm_secp256r1_hash,
    zkvm_secp256r1_pubkey, zkvm_secp256r1_signature, zkvm_sha256_hash, zkvm_status,
    zkvm_status_ZKVM_EFAIL as ZKVM_EFAIL, zkvm_status_ZKVM_EOK as ZKVM_EOK,
};

// Generated by `cargo openvm` for standard `SdkVmConfig`. Hosting it here to force guest
// to use the same VM config.
mod openvm_init {
    openvm_algebra_guest::moduli_macros::moduli_init! { "21888242871839275222246405745257275088696311157297823662689037894645226208583", "21888242871839275222246405745257275088548364400416034343698204186575808495617", "115792089237316195423570985008687907853269984665640564039457584007908834671663", "115792089237316195423570985008687907852837564279074904382605163141518161494337", "115792089210356248762697446949407573530086143415290314195533631308867097853951", "115792089210356248762697446949407573529996955224135760342422259061068512044369", "4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787", "52435875175126190479447740508185965837690552500527637822603658699938581184513" }
    openvm_algebra_guest::complex_macros::complex_init! { "Bn254Fp2" { mod_idx = 0 }, "Bls12_381Fp2" { mod_idx = 6 } }
    openvm_ecc_guest::sw_macros::sw_init! { "Bn254G1Affine", "Secp256k1Point", "P256Point", "Bls12_381G1Affine" }
}

const BN_FQ_LEN: usize = 32;
const BN_G1_LEN: usize = 64;
const BN_G2_LEN: usize = 128;
const BN_SCALAR_LEN: usize = 32;

const BLS_FP_LEN: usize = 48;
const BLS_G1_LEN: usize = 96;
const BLS_G2_LEN: usize = 192;
const BLS_SCALAR_LEN: usize = 32;

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_keccak256(
    data: *const u8,
    len: usize,
    output: *mut zkvm_keccak256_hash,
) -> zkvm_status {
    unsafe { (*output).data = keccak256(slice::from_raw_parts(data, len)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_secp256k1_verify(
    msg: *const zkvm_secp256k1_hash,
    sig: *const zkvm_secp256k1_signature,
    pubkey: *const zkvm_secp256k1_pubkey,
    verified: *mut bool,
) -> zkvm_status {
    unsafe { *verified = verify_secp256k1(&(*msg).data, &(*sig).data, &(*pubkey).data) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_secp256k1_ecrecover(
    msg: *const zkvm_secp256k1_hash,
    sig: *const zkvm_secp256k1_signature,
    mut recid: u8,
    output: *mut zkvm_secp256k1_pubkey,
) -> zkvm_status {
    let (msg, sig) = unsafe { (&(*msg).data, &(*sig).data) };

    let Ok(mut signature) = Signature::from_slice(sig) else {
        return ZKVM_EFAIL;
    };

    if let Some(signature_normalized) = signature.normalize_s() {
        signature = signature_normalized;
        recid ^= 1;
    }

    let Some(recovery_id) = RecoveryId::from_byte(recid) else {
        return ZKVM_EFAIL;
    };

    let Ok(recovered_key) =
        VerifyingKey::recover_from_prehash_noverify(msg, &signature.to_bytes(), recovery_id)
    else {
        return ZKVM_EFAIL;
    };

    // The uncompressed SEC1 key without the `0x04` prefix.
    let public_key = recovered_key.to_encoded_point(false);
    unsafe { (*output).data = public_key.as_bytes()[1..65].try_into().unwrap() };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_sha256(
    data: *const u8,
    len: usize,
    output: *mut zkvm_sha256_hash,
) -> zkvm_status {
    unsafe { (*output).data = Sha256::digest(slice::from_raw_parts(data, len)).into() };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_ripemd160(
    data: *const u8,
    len: usize,
    output: *mut zkvm_ripemd160_hash,
) -> zkvm_status {
    let digest = Ripemd160::digest(unsafe { slice::from_raw_parts(data, len) });
    // The C interface right-aligns the 20-byte digest in 32 bytes.
    let mut hash = [0u8; 32];
    hash[12..].copy_from_slice(&digest);
    unsafe { (*output).data = hash };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_modexp(
    base: *const u8,
    base_len: usize,
    exp: *const u8,
    exp_len: usize,
    modulus: *const u8,
    mod_len: usize,
    output: *mut u8,
) -> zkvm_status {
    let (base, exp, modulus) = unsafe {
        (
            slice::from_raw_parts(base, base_len),
            slice::from_raw_parts(exp, exp_len),
            slice::from_raw_parts(modulus, mod_len),
        )
    };

    let result = if is_bn254_fr(modulus) {
        accelerated_modexp_bn254_fr(base, exp)
    } else {
        aurora_engine_modexp::modexp(base, exp, modulus)
    };

    // EIP-198 defines the output as exactly `mod_len` bytes, left-padded with zeros.
    let output = unsafe { slice::from_raw_parts_mut(output, mod_len) };
    let offset = mod_len - result.len();
    output[..offset].fill(0);
    output[offset..].copy_from_slice(&result);
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bn254_g1_add(
    p1: *const zkvm_bn254_g1_point,
    p2: *const zkvm_bn254_g1_point,
    result: *mut zkvm_bn254_g1_point,
) -> zkvm_status {
    let Some(p1) = (unsafe { read_bn_g1_point(&(*p1).data) }) else {
        return ZKVM_EFAIL;
    };
    let Some(p2) = (unsafe { read_bn_g1_point(&(*p2).data) }) else {
        return ZKVM_EFAIL;
    };
    unsafe { (*result).data = encode_bn_g1_point(p1 + p2) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bn254_g1_mul(
    point: *const zkvm_bn254_g1_point,
    scalar: *const zkvm_bn254_scalar,
    result: *mut zkvm_bn254_g1_point,
) -> zkvm_status {
    let Some(point) = (unsafe { read_bn_g1_point(&(*point).data) }) else {
        return ZKVM_EFAIL;
    };
    let scalar = unsafe { read_bn_scalar(&(*scalar).data) };
    unsafe { (*result).data = encode_bn_g1_point(Bn254::msm(&[scalar], &[point])) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bn254_pairing(
    pairs: *const zkvm_bn254_pairing_pair,
    num_pairs: usize,
    verified: *mut bool,
) -> zkvm_status {
    if num_pairs == 0 {
        unsafe { *verified = true };
        return ZKVM_EOK;
    }

    let mut g1_points = Vec::with_capacity(num_pairs);
    let mut g2_points = Vec::with_capacity(num_pairs);
    for pair in unsafe { slice::from_raw_parts(pairs, num_pairs) } {
        let Some(g1) = read_bn_g1_point(&pair.g1.data) else {
            return ZKVM_EFAIL;
        };
        let Some(g2) = read_bn_g2_point(&pair.g2.data) else {
            return ZKVM_EFAIL;
        };
        let (g1_x, g1_y) = g1.into_coords();
        let (g2_x, g2_y) = g2.into_coords();
        g1_points.push(AffinePoint::new(g1_x, g1_y));
        g2_points.push(AffinePoint::new(g2_x, g2_y));
    }

    unsafe { *verified = Bn254::pairing_check(&g1_points, &g2_points).is_ok() };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_blake2f(
    rounds: u32,
    h: *mut zkvm_blake2f_state,
    m: *const zkvm_blake2f_message,
    t: *const zkvm_blake2f_offset,
    f: u8,
) -> zkvm_status {
    let mut state = [0u64; 8];
    let mut message = [0u64; 16];
    let mut offset = [0u64; 2];
    unsafe {
        read_u64_le(&(*h).data, &mut state);
        read_u64_le(&(*m).data, &mut message);
        read_u64_le(&(*t).data, &mut offset);
    }

    blake2::compress(rounds, &mut state, &message, &offset, f != 0);

    unsafe { write_u64_le(&state, &mut (*h).data) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_kzg_point_eval(
    commitment: *const zkvm_kzg_commitment,
    z: *const zkvm_kzg_field_element,
    y: *const zkvm_kzg_field_element,
    proof: *const zkvm_kzg_proof,
    verified: *mut bool,
) -> zkvm_status {
    // `from_slice` is the only constructor and rejects lengths other than its own.
    let (commitment, z, y, proof) = unsafe {
        (
            Bytes48::from_slice(&(*commitment).data).unwrap(),
            Bytes32::from_slice(&(*z).data).unwrap(),
            Bytes32::from_slice(&(*y).data).unwrap(),
            Bytes48::from_slice(&(*proof).data).unwrap(),
        )
    };

    let env = EnvKzgSettings::default();
    unsafe {
        *verified = matches!(
            KzgProof::verify_kzg_proof(&commitment, &z, &y, &proof, env.get()),
            Ok(true)
        )
    };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_g1_add(
    p1: *const zkvm_bls12_381_g1_point,
    p2: *const zkvm_bls12_381_g1_point,
    result: *mut zkvm_bls12_381_g1_point,
) -> zkvm_status {
    // EIP-2537 G1ADD validates on-curve only, not subgroup membership.
    let Some(p1) = (unsafe { read_bls_g1_point_no_subgroup_check(&(*p1).data) }) else {
        return ZKVM_EFAIL;
    };
    let Some(p2) = (unsafe { read_bls_g1_point_no_subgroup_check(&(*p2).data) }) else {
        return ZKVM_EFAIL;
    };
    unsafe { (*result).data = encode_bls_g1_point(&(p1 + p2)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_g1_msm(
    pairs: *const zkvm_bls12_381_g1_msm_pair,
    num_pairs: usize,
    result: *mut zkvm_bls12_381_g1_point,
) -> zkvm_status {
    if num_pairs == 0 {
        unsafe { (*result).data = [0u8; BLS_G1_LEN] };
        return ZKVM_EOK;
    }

    let mut points = Vec::with_capacity(num_pairs);
    let mut scalars = Vec::with_capacity(num_pairs);
    for pair in unsafe { slice::from_raw_parts(pairs, num_pairs) } {
        let Some(point) = read_bls_g1_point(&pair.point.data) else {
            return ZKVM_EFAIL;
        };
        points.push(point);
        scalars.push(read_bls_scalar(&pair.scalar.data));
    }

    unsafe { (*result).data = encode_bls_g1_point(&Bls12_381::msm(&scalars, &points)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_g2_add(
    p1: *const zkvm_bls12_381_g2_point,
    p2: *const zkvm_bls12_381_g2_point,
    result: *mut zkvm_bls12_381_g2_point,
) -> zkvm_status {
    // EIP-2537 G2ADD validates on-curve only, not subgroup membership.
    let Some(p1) = (unsafe { read_bls_g2_point_no_subgroup_check(&(*p1).data) }) else {
        return ZKVM_EFAIL;
    };
    let Some(p2) = (unsafe { read_bls_g2_point_no_subgroup_check(&(*p2).data) }) else {
        return ZKVM_EFAIL;
    };
    unsafe { (*result).data = encode_bls_g2_point(&(p1 + p2)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_g2_msm(
    pairs: *const zkvm_bls12_381_g2_msm_pair,
    num_pairs: usize,
    result: *mut zkvm_bls12_381_g2_point,
) -> zkvm_status {
    if num_pairs == 0 {
        unsafe { (*result).data = [0u8; BLS_G2_LEN] };
        return ZKVM_EOK;
    }

    let mut points = Vec::with_capacity(num_pairs);
    let mut scalars = Vec::with_capacity(num_pairs);
    for pair in unsafe { slice::from_raw_parts(pairs, num_pairs) } {
        let Some(point) = read_bls_g2_point(&pair.point.data) else {
            return ZKVM_EFAIL;
        };
        points.push(point);
        scalars.push(read_bls_scalar(&pair.scalar.data));
    }

    unsafe { (*result).data = encode_bls_g2_point(&openvm_ecc_guest::msm(&scalars, &points)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_pairing(
    pairs: *const zkvm_bls12_381_pairing_pair,
    num_pairs: usize,
    verified: *mut bool,
) -> zkvm_status {
    if num_pairs == 0 {
        unsafe { *verified = true };
        return ZKVM_EOK;
    }

    let mut g1_points = Vec::with_capacity(num_pairs);
    let mut g2_points = Vec::with_capacity(num_pairs);
    for pair in unsafe { slice::from_raw_parts(pairs, num_pairs) } {
        let Some(g1) = read_bls_g1_point(&pair.g1.data) else {
            return ZKVM_EFAIL;
        };
        let Some(g2) = read_bls_g2_point(&pair.g2.data) else {
            return ZKVM_EFAIL;
        };
        let (g1_x, g1_y) = g1.into_coords();
        let (g2_x, g2_y) = g2.into_coords();
        g1_points.push(AffinePoint::new(g1_x, g1_y));
        g2_points.push(AffinePoint::new(g2_x, g2_y));
    }

    unsafe { *verified = Bls12_381::pairing_check(&g1_points, &g2_points).is_ok() };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_map_fp_to_g1(
    field_element: *const zkvm_bls12_381_fp,
    result: *mut zkvm_bls12_381_g1_point,
) -> zkvm_status {
    let Some(field_element) = read_bls12_fp(unsafe { &(*field_element).data }) else {
        return ZKVM_EFAIL;
    };

    unsafe { (*result).data = serialize_bls12_g1(&map_bls12_fp_to_g1(field_element)) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_bls12_map_fp2_to_g2(
    field_element: *const zkvm_bls12_381_fp2,
    result: *mut zkvm_bls12_381_g2_point,
) -> zkvm_status {
    let field_element = unsafe { &(*field_element).data };
    let Some(c0) = read_bls12_fp(field_element[..BLS_FP_LEN].try_into().unwrap()) else {
        return ZKVM_EFAIL;
    };
    let Some(c1) = read_bls12_fp(field_element[BLS_FP_LEN..].try_into().unwrap()) else {
        return ZKVM_EFAIL;
    };

    unsafe { (*result).data = serialize_bls12_g2(&map_bls12_fp2_to_g2(Fq2::new(c0, c1))) };
    ZKVM_EOK
}

#[unsafe(no_mangle)]
unsafe extern "C" fn zkvm_secp256r1_verify(
    msg: *const zkvm_secp256r1_hash,
    sig: *const zkvm_secp256r1_signature,
    pubkey: *const zkvm_secp256r1_pubkey,
    verified: *mut bool,
) -> zkvm_status {
    unsafe { *verified = verify_secp256r1(&(*msg).data, &(*sig).data, &(*pubkey).data) };
    ZKVM_EOK
}

fn verify_secp256k1(msg: &[u8; 32], sig: &[u8; 64], pubkey: &[u8; 64]) -> bool {
    // `from_slice` rejects zero and non-canonical r/s scalars.
    let Ok(signature) = Signature::from_slice(sig) else {
        return false;
    };
    // Plain-ECDSA semantics accept high-s signatures while `verify_prehash` enforces the low-s
    // rule, so normalize first. `(r, n - s)` verifies exactly when `(r, s)` does.
    let signature = signature.normalize_s().unwrap_or(signature);

    // The C interface carries the uncompressed public key without the SEC1 `0x04` tag.
    let mut sec1 = [0u8; 65];
    sec1[0] = 0x04;
    sec1[1..].copy_from_slice(pubkey);
    let Ok(verifying_key) = VerifyingKey::from_sec1_bytes(&sec1) else {
        return false;
    };

    verifying_key.verify_prehash(msg, &signature).is_ok()
}

fn verify_secp256r1(msg: &[u8; 32], sig: &[u8; 64], pubkey: &[u8; 64]) -> bool {
    // `from_slice` rejects zero and non-canonical r/s scalars.
    let Ok(signature) = P256Signature::from_slice(sig) else {
        return false;
    };

    let encoded_point =
        EncodedPoint::from_affine_coordinates(pubkey[..32].into(), pubkey[32..].into(), false);
    let Ok(verifying_key) = P256VerifyingKey::from_encoded_point(&encoded_point) else {
        return false;
    };

    verifying_key.verify_prehash(msg, &signature).is_ok()
}

/// Returns true if the modulus (big-endian, possibly with leading zeros) equals BN254 Fr.
fn is_bn254_fr(modulus: &[u8]) -> bool {
    // Strip leading zeros
    let stripped = match modulus.iter().position(|&b| b != 0) {
        Some(i) => &modulus[i..],
        None => return false, // all zeros
    };
    // bn::Scalar::MODULUS is little-endian, so compare against the reversed input
    stripped.len() == BN_SCALAR_LEN
        && stripped
            .iter()
            .rev()
            .eq(bn::Scalar::MODULUS.as_ref().iter())
}

/// Accelerated modexp for BN254 Fr using field arithmetic intrinsics.
fn accelerated_modexp_bn254_fr(base: &[u8], exp: &[u8]) -> Vec<u8> {
    use openvm_ecc_guest::algebra::{ExpBytes, Reduce};

    // OpenVM's field reduction requires inputs to be aligned to the field byte size.
    let padded_len = base
        .len()
        .next_multiple_of(BN_SCALAR_LEN)
        .max(BN_SCALAR_LEN);
    let mut padded = vec![0u8; padded_len];
    padded[padded_len - base.len()..].copy_from_slice(base);
    let base_fr = bn::Scalar::reduce_be_bytes(&padded);

    let result = base_fr.exp_bytes(true, exp);
    result.assert_reduced();
    result.to_be_bytes().as_ref().to_vec()
}

#[inline]
fn read_bn_fq(input: &[u8]) -> Option<bn::Fp> {
    bn::Fp::from_be_bytes(input)
}

#[inline]
fn read_bn_fq2(input: &[u8]) -> Option<bn::Fp2> {
    let y = read_bn_fq(&input[..BN_FQ_LEN])?;
    let x = read_bn_fq(&input[BN_FQ_LEN..BN_FQ_LEN * 2])?;
    Some(bn::Fp2::new(x, y))
}

#[inline]
fn read_bn_g1_point(input: &[u8; BN_G1_LEN]) -> Option<bn::G1Affine> {
    let px = read_bn_fq(&input[..BN_FQ_LEN])?;
    let py = read_bn_fq(&input[BN_FQ_LEN..])?;
    // SAFETY: `read_bn_fq` produces canonical Fp elements. `from_xy` itself checks the curve
    // equation and returns `None` if `(px, py)` is not on the curve.
    let point = unsafe { bn::G1Affine::from_xy(px, py) }?;
    point.is_in_correct_subgroup().then_some(point)
}

#[inline]
fn read_bn_g2_point(input: &[u8; BN_G2_LEN]) -> Option<bn::G2Affine> {
    let c0 = read_bn_fq2(&input[..BN_G1_LEN])?;
    let c1 = read_bn_fq2(&input[BN_G1_LEN..])?;
    // SAFETY: `read_bn_fq2` produces canonical Fp2 elements. `from_xy` itself checks the curve
    // equation and returns `None` if `(c0, c1)` is not on the twist.
    let point = unsafe { bn::G2Affine::from_xy(c0, c1) }?;
    point.is_in_correct_subgroup().then_some(point)
}

#[inline]
fn encode_bn_g1_point(point: bn::G1Affine) -> [u8; BN_G1_LEN] {
    let mut output = [0u8; BN_G1_LEN];
    point.x().assert_reduced();
    point.y().assert_reduced();
    let x_bytes: &[u8] = point.x().as_le_bytes();
    let y_bytes: &[u8] = point.y().as_le_bytes();
    for i in 0..BN_FQ_LEN {
        output[i] = x_bytes[BN_FQ_LEN - 1 - i];
        output[i + BN_FQ_LEN] = y_bytes[BN_FQ_LEN - 1 - i];
    }
    output
}

/// Reads a scalar from the input bytes. The scalar does not need to be canonical.
#[inline]
fn read_bn_scalar(input: &[u8; BN_SCALAR_LEN]) -> bn::Scalar {
    bn::Scalar::from_be_bytes_unchecked(input)
}

#[inline]
fn read_bls_fp(input: &[u8]) -> Option<bls::Fp> {
    bls::Fp::from_be_bytes(input)
}

#[inline]
fn read_bls_fp2(c0: &[u8], c1: &[u8]) -> Option<bls::Fp2> {
    let real = read_bls_fp(c0)?;
    let imag = read_bls_fp(c1)?;
    Some(bls::Fp2::new(real, imag))
}

#[inline]
fn read_bls_g1_point_no_subgroup_check(input: &[u8; BLS_G1_LEN]) -> Option<bls::G1Affine> {
    let px = read_bls_fp(&input[..BLS_FP_LEN])?;
    let py = read_bls_fp(&input[BLS_FP_LEN..])?;
    // SAFETY: `read_bls_fp` produces canonical Fp elements. `from_xy` itself checks the curve
    // equation and returns `None` if `(px, py)` is not on the curve.
    unsafe { bls::G1Affine::from_xy(px, py) }
}

#[inline]
fn read_bls_g1_point(input: &[u8; BLS_G1_LEN]) -> Option<bls::G1Affine> {
    let point = read_bls_g1_point_no_subgroup_check(input)?;
    point.is_in_correct_subgroup().then_some(point)
}

#[inline]
fn read_bls_g2_point_no_subgroup_check(input: &[u8; BLS_G2_LEN]) -> Option<bls::G2Affine> {
    let x = read_bls_fp2(&input[..BLS_FP_LEN], &input[BLS_FP_LEN..2 * BLS_FP_LEN])?;
    let y = read_bls_fp2(
        &input[2 * BLS_FP_LEN..3 * BLS_FP_LEN],
        &input[3 * BLS_FP_LEN..],
    )?;
    // SAFETY: `read_bls_fp2` produces canonical Fp2 elements. `from_xy` itself checks the curve
    // equation and returns `None` if `(x, y)` is not on the twist.
    unsafe { bls::G2Affine::from_xy(x, y) }
}

#[inline]
fn read_bls_g2_point(input: &[u8; BLS_G2_LEN]) -> Option<bls::G2Affine> {
    let point = read_bls_g2_point_no_subgroup_check(input)?;
    point.is_in_correct_subgroup().then_some(point)
}

/// Reads a scalar from the input bytes. The scalar does not need to be canonical.
#[inline]
fn read_bls_scalar(input: &[u8; BLS_SCALAR_LEN]) -> bls::Scalar {
    bls::Scalar::from_be_bytes_unchecked(input)
}

#[inline]
fn encode_bls_g1_point(point: &bls::G1Affine) -> [u8; BLS_G1_LEN] {
    if point.is_identity() {
        return [0u8; BLS_G1_LEN];
    }

    let mut output = [0u8; BLS_G1_LEN];
    point.x().assert_reduced();
    point.y().assert_reduced();
    let x_bytes: &[u8] = point.x().as_le_bytes();
    let y_bytes: &[u8] = point.y().as_le_bytes();
    for i in 0..BLS_FP_LEN {
        output[i] = x_bytes[BLS_FP_LEN - 1 - i];
        output[i + BLS_FP_LEN] = y_bytes[BLS_FP_LEN - 1 - i];
    }
    output
}

#[inline]
fn encode_bls_g2_point(point: &bls::G2Affine) -> [u8; BLS_G2_LEN] {
    if point.is_identity() {
        return [0u8; BLS_G2_LEN];
    }

    let mut output = [0u8; BLS_G2_LEN];
    let x = point.x();
    let y = point.y();
    x.c0.assert_reduced();
    x.c1.assert_reduced();
    y.c0.assert_reduced();
    y.c1.assert_reduced();
    let x_c0 = x.c0.as_le_bytes();
    let x_c1 = x.c1.as_le_bytes();
    let y_c0 = y.c0.as_le_bytes();
    let y_c1 = y.c1.as_le_bytes();
    for i in 0..BLS_FP_LEN {
        output[i] = x_c0[BLS_FP_LEN - 1 - i];
        output[i + BLS_FP_LEN] = x_c1[BLS_FP_LEN - 1 - i];
        output[i + (2 * BLS_FP_LEN)] = y_c0[BLS_FP_LEN - 1 - i];
        output[i + (3 * BLS_FP_LEN)] = y_c1[BLS_FP_LEN - 1 - i];
    }
    output
}

/// Reads a big-endian `Fp`, rejecting an encoding that is not the canonical representative.
fn read_bls12_fp(input: &[u8; BLS_FP_LEN]) -> Option<Fq> {
    let mut input_le = *input;
    input_le.reverse();
    Fq::deserialize_uncompressed(&input_le[..]).ok()
}

/// Serializes an `Fp` as 48 big-endian bytes.
fn encode_bls12_fp(fp: &Fq) -> [u8; BLS_FP_LEN] {
    let mut output = [0u8; BLS_FP_LEN];
    fp.serialize_uncompressed(&mut output[..])
        .expect("a field element always serializes");
    output.reverse();
    output
}

/// Maps an `Fp` onto G1 following EIP-2537, which is the simplified SWU map composed with the
/// isogeny back to the curve, then cofactor clearing.
fn map_bls12_fp_to_g1(fp: Fq) -> G1Affine {
    WBMap::map_to_curve(fp)
        .expect("map_to_curve is infallible")
        .clear_cofactor()
}

/// Maps an `Fp2` onto G2 following EIP-2537.
fn map_bls12_fp2_to_g2(fp2: Fq2) -> G2Affine {
    WBMap::map_to_curve(fp2)
        .expect("map_to_curve is infallible")
        .clear_cofactor()
}

/// Serializes a G1 point as `x || y`, each 48 big-endian bytes, with infinity as all zeros.
fn serialize_bls12_g1(point: &G1Affine) -> [u8; BLS_G1_LEN] {
    let mut output = [0u8; BLS_G1_LEN];
    let Some((x, y)) = point.xy() else {
        return output;
    };
    output[..BLS_FP_LEN].copy_from_slice(&encode_bls12_fp(&x));
    output[BLS_FP_LEN..].copy_from_slice(&encode_bls12_fp(&y));
    output
}

/// Serializes a G2 point as `x_c0 || x_c1 || y_c0 || y_c1`, each 48 big-endian bytes, with
/// infinity as all zeros.
fn serialize_bls12_g2(point: &G2Affine) -> [u8; BLS_G2_LEN] {
    let mut output = [0u8; BLS_G2_LEN];
    let Some((x, y)) = point.xy() else {
        return output;
    };
    output[..BLS_FP_LEN].copy_from_slice(&encode_bls12_fp(&x.c0));
    output[BLS_FP_LEN..2 * BLS_FP_LEN].copy_from_slice(&encode_bls12_fp(&x.c1));
    output[2 * BLS_FP_LEN..3 * BLS_FP_LEN].copy_from_slice(&encode_bls12_fp(&y.c0));
    output[3 * BLS_FP_LEN..].copy_from_slice(&encode_bls12_fp(&y.c1));
    output
}

/// Decodes little-endian `u64` words out of `bytes`.
fn read_u64_le(bytes: &[u8], words: &mut [u64]) {
    for (word, bytes) in words.iter_mut().zip(bytes.as_chunks::<8>().0) {
        *word = u64::from_le_bytes(*bytes);
    }
}

/// Encodes `words` as little-endian `u64` into `bytes`.
fn write_u64_le(words: &[u64], bytes: &mut [u8]) {
    for (word, bytes) in words.iter().zip(bytes.as_chunks_mut::<8>().0) {
        *bytes = word.to_le_bytes();
    }
}

/// BLAKE2b compression function F, copied and modified from [`revm-precompile`]
///
/// [`revm-precompile`]: https://github.com/bluealloy/revm/blob/main/crates/precompile/src/blake2/portable.rs
mod blake2 {
    // Adapted from https://github.com/oconnor663/blake2_simd
    // Copyright (c) 2018 Jack O'Connor
    // Licensed under the MIT license

    type Word = u64;

    const IV: [Word; 8] = [
        0x6A09E667F3BCC908,
        0xBB67AE8584CAA73B,
        0x3C6EF372FE94F82B,
        0xA54FF53A5F1D36F1,
        0x510E527FADE682D1,
        0x9B05688C2B3E6C1F,
        0x1F83D9ABFB41BD6B,
        0x5BE0CD19137E2179,
    ];

    const SIGMA: [[u8; 16]; 10] = [
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
        [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
        [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
        [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
        [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
        [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
        [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
        [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
        [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
    ];

    #[inline(always)]
    const fn g(v: &mut [Word; 16], a: usize, b: usize, c: usize, d: usize, x: Word, y: Word) {
        v[a] = v[a].wrapping_add(v[b]).wrapping_add(x);
        v[d] = (v[d] ^ v[a]).rotate_right(32);
        v[c] = v[c].wrapping_add(v[d]);
        v[b] = (v[b] ^ v[c]).rotate_right(24);
        v[a] = v[a].wrapping_add(v[b]).wrapping_add(y);
        v[d] = (v[d] ^ v[a]).rotate_right(16);
        v[c] = v[c].wrapping_add(v[d]);
        v[b] = (v[b] ^ v[c]).rotate_right(63);
    }

    #[inline(always)]
    const fn round(r: usize, m: &[Word; 16], v: &mut [Word; 16]) {
        let s = SIGMA[r % 10];

        g(v, 0, 4, 8, 12, m[s[0] as usize], m[s[1] as usize]);
        g(v, 1, 5, 9, 13, m[s[2] as usize], m[s[3] as usize]);
        g(v, 2, 6, 10, 14, m[s[4] as usize], m[s[5] as usize]);
        g(v, 3, 7, 11, 15, m[s[6] as usize], m[s[7] as usize]);

        g(v, 0, 5, 10, 15, m[s[8] as usize], m[s[9] as usize]);
        g(v, 1, 6, 11, 12, m[s[10] as usize], m[s[11] as usize]);
        g(v, 2, 7, 8, 13, m[s[12] as usize], m[s[13] as usize]);
        g(v, 3, 4, 9, 14, m[s[14] as usize], m[s[15] as usize]);
    }

    pub fn compress(rounds: u32, words: &mut [Word; 8], m: &[Word; 16], t: &[Word; 2], f: bool) {
        let mut v = [
            words[0],
            words[1],
            words[2],
            words[3],
            words[4],
            words[5],
            words[6],
            words[7],
            IV[0],
            IV[1],
            IV[2],
            IV[3],
            IV[4] ^ t[0],
            IV[5] ^ t[1],
            IV[6] ^ if f { !0 } else { 0 },
            IV[7],
        ];

        for i in 0..rounds as usize {
            round(i, m, &mut v);
        }

        words[0] ^= v[0] ^ v[8];
        words[1] ^= v[1] ^ v[9];
        words[2] ^= v[2] ^ v[10];
        words[3] ^= v[3] ^ v[11];
        words[4] ^= v[4] ^ v[12];
        words[5] ^= v[5] ^ v[13];
        words[6] ^= v[6] ^ v[14];
        words[7] ^= v[7] ^ v[15];
    }
}
