// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub input_stdin: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub input_proofs: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResponse {
    #[prost(oneof = "execute_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<execute_response::Result>,
}
/// Nested message and enum types in `ExecuteResponse`.
pub mod execute_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ok(super::ExecuteOk),
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteOk {
    #[prost(bytes = "vec", tag = "1")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub duration_nanos: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteEstimatedCostRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub input_stdin: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub input_proofs: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteEstimatedCostResponse {
    #[prost(oneof = "execute_estimated_cost_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<execute_estimated_cost_response::Result>,
}
/// Nested message and enum types in `ExecuteEstimatedCostResponse`.
pub mod execute_estimated_cost_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ok(super::ExecuteEstimatedCostOk),
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteEstimatedCostOk {
    #[prost(bytes = "vec", tag = "1")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, uint64", tag = "2")]
    pub cost: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
    #[prost(uint64, optional, tag = "3")]
    pub peak_heap_bytes: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProveRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub input_stdin: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub input_proofs: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProveResponse {
    #[prost(oneof = "prove_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<prove_response::Result>,
}
/// Nested message and enum types in `ProveResponse`.
pub mod prove_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ok(super::ProveOk),
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProveOk {
    #[prost(bytes = "vec", tag = "1")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub duration_nanos: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyResponse {
    #[prost(oneof = "verify_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<verify_response::Result>,
}
/// Nested message and enum types in `VerifyResponse`.
pub mod verify_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ok(super::VerifyOk),
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyOk {
    #[prost(bytes = "vec", tag = "1")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgramVkRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgramVkResponse {
    #[prost(oneof = "program_vk_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<program_vk_response::Result>,
}
/// Nested message and enum types in `ProgramVkResponse`.
pub mod program_vk_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Ok(super::ProgramVkOk),
        #[prost(string, tag = "2")]
        Err(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgramVkOk {
    #[prost(bytes = "vec", tag = "1")]
    pub program_vk: ::prost::alloc::vec::Vec<u8>,
}
pub use twirp;
#[twirp::async_trait::async_trait]
pub trait ZkvmService: Send + Sync {
    async fn execute(
        &self,
        req: twirp::Request<ExecuteRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteResponse>>;
    async fn execute_estimated_cost(
        &self,
        req: twirp::Request<ExecuteEstimatedCostRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteEstimatedCostResponse>>;
    async fn prove(
        &self,
        req: twirp::Request<ProveRequest>,
    ) -> twirp::Result<twirp::Response<ProveResponse>>;
    async fn verify(
        &self,
        req: twirp::Request<VerifyRequest>,
    ) -> twirp::Result<twirp::Response<VerifyResponse>>;
    async fn program_vk(
        &self,
        req: twirp::Request<ProgramVkRequest>,
    ) -> twirp::Result<twirp::Response<ProgramVkResponse>>;
}
#[twirp::async_trait::async_trait]
impl<T> ZkvmService for std::sync::Arc<T>
where
    T: ZkvmService + Sync + Send,
{
    async fn execute(
        &self,
        req: twirp::Request<ExecuteRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteResponse>> {
        T::execute(&*self, req).await
    }
    async fn execute_estimated_cost(
        &self,
        req: twirp::Request<ExecuteEstimatedCostRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteEstimatedCostResponse>> {
        T::execute_estimated_cost(&*self, req).await
    }
    async fn prove(
        &self,
        req: twirp::Request<ProveRequest>,
    ) -> twirp::Result<twirp::Response<ProveResponse>> {
        T::prove(&*self, req).await
    }
    async fn verify(
        &self,
        req: twirp::Request<VerifyRequest>,
    ) -> twirp::Result<twirp::Response<VerifyResponse>> {
        T::verify(&*self, req).await
    }
    async fn program_vk(
        &self,
        req: twirp::Request<ProgramVkRequest>,
    ) -> twirp::Result<twirp::Response<ProgramVkResponse>> {
        T::program_vk(&*self, req).await
    }
}
pub fn router<T>(api: T) -> twirp::Router
where
    T: ZkvmService + Clone + Send + Sync + 'static,
{
    twirp::details::TwirpRouterBuilder::new("/api.ZkvmService", api)
        .route(
            "/Execute",
            |api: T, req: twirp::Request<ExecuteRequest>| async move {
                api.execute(req).await
            },
        )
        .route(
            "/ExecuteEstimatedCost",
            |api: T, req: twirp::Request<ExecuteEstimatedCostRequest>| async move {
                api.execute_estimated_cost(req).await
            },
        )
        .route(
            "/Prove",
            |api: T, req: twirp::Request<ProveRequest>| async move {
                api.prove(req).await
            },
        )
        .route(
            "/Verify",
            |api: T, req: twirp::Request<VerifyRequest>| async move {
                api.verify(req).await
            },
        )
        .route(
            "/ProgramVk",
            |api: T, req: twirp::Request<ProgramVkRequest>| async move {
                api.program_vk(req).await
            },
        )
        .build()
}
#[twirp::async_trait::async_trait]
impl ZkvmService for twirp::client::Client {
    async fn execute(
        &self,
        req: twirp::Request<ExecuteRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteResponse>> {
        self.request("api.ZkvmService/Execute", req).await
    }
    async fn execute_estimated_cost(
        &self,
        req: twirp::Request<ExecuteEstimatedCostRequest>,
    ) -> twirp::Result<twirp::Response<ExecuteEstimatedCostResponse>> {
        self.request("api.ZkvmService/ExecuteEstimatedCost", req).await
    }
    async fn prove(
        &self,
        req: twirp::Request<ProveRequest>,
    ) -> twirp::Result<twirp::Response<ProveResponse>> {
        self.request("api.ZkvmService/Prove", req).await
    }
    async fn verify(
        &self,
        req: twirp::Request<VerifyRequest>,
    ) -> twirp::Result<twirp::Response<VerifyResponse>> {
        self.request("api.ZkvmService/Verify", req).await
    }
    async fn program_vk(
        &self,
        req: twirp::Request<ProgramVkRequest>,
    ) -> twirp::Result<twirp::Response<ProgramVkResponse>> {
        self.request("api.ZkvmService/ProgramVk", req).await
    }
}
#[allow(dead_code)]
pub mod handler {
    use super::*;
    pub struct ZkvmServiceHandler {
        inner: std::sync::Arc<dyn ZkvmService>,
    }
    impl ZkvmServiceHandler {
        #[allow(clippy::new_ret_no_self)]
        pub fn new<M: ZkvmService + 'static>(inner: M) -> Self {
            Self {
                inner: std::sync::Arc::new(inner),
            }
        }
    }
    #[twirp::async_trait::async_trait]
    impl twirp::client::DirectHandler for ZkvmServiceHandler {
        fn service(&self) -> &str {
            "api.ZkvmService"
        }
        async fn handle(
            &self,
            method: &str,
            req: twirp::reqwest::Request,
        ) -> twirp::Result<twirp::reqwest::Response> {
            match method {
                "Execute" => {
                    twirp::details::encode_response(
                        self
                            .inner
                            .execute(twirp::details::decode_request(req).await?)
                            .await?,
                    )
                }
                "ExecuteEstimatedCost" => {
                    twirp::details::encode_response(
                        self
                            .inner
                            .execute_estimated_cost(
                                twirp::details::decode_request(req).await?,
                            )
                            .await?,
                    )
                }
                "Prove" => {
                    twirp::details::encode_response(
                        self
                            .inner
                            .prove(twirp::details::decode_request(req).await?)
                            .await?,
                    )
                }
                "Verify" => {
                    twirp::details::encode_response(
                        self
                            .inner
                            .verify(twirp::details::decode_request(req).await?)
                            .await?,
                    )
                }
                "ProgramVk" => {
                    twirp::details::encode_response(
                        self
                            .inner
                            .program_vk(twirp::details::decode_request(req).await?)
                            .await?,
                    )
                }
                _ => {
                    Err(
                        twirp::bad_route(
                            format!(
                                "unknown rpc `{method}` for service `{}`, url: {:?}",
                                "api.ZkvmService", req.url()
                            ),
                        ),
                    )
                }
            }
        }
    }
}
